# Generated by Django 5.0.1 on 2024-01-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('item_image', models.ImageField(upload_to='item/')),
            ],
        ),
    ]
