# Generated by Django 5.0.1 on 2024-01-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marApp', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
