# Generated by Django 5.0.2 on 2024-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marApp', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(blank=True, max_length=15, null=True)),
                ('reservation_surname', models.CharField(blank=True, max_length=15, null=True)),
                ('reservation_position', models.CharField(blank=True, max_length=20, null=True)),
                ('reservation_email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
