# Generated by Django 5.0.2 on 2024-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marApp', '0006_reservation_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_position',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_surname',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
    ]
