# Generated by Django 5.0.2 on 2024-02-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marApp', '0007_remove_reservation_reservation_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
