# Generated by Django 5.0.2 on 2024-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marApp', '0008_reservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_people',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
